version: 0.0

#윈도우, 리눅스 등 어떤 OS위한 배포파일인지 명시
os: linux

#CodeDeploy될때 프로젝트 전체를 서버의 특정 경로로 내려받게 하기위해서 명시하는 부분
files:
 - source: /
   destination: /dev/
   
#AppSpec.yml에서는 배포시 발생하는 다양한 생명 주기마다 원하는 스크립트를 실행할수 있게 후크를 제공함
#배포시 사용하는 스크립트들은 원하는곳에 둬도 되는데 보통 프로젝트에 appspec.yml파일을 포함하듯이 포함한다.